version: "2"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8001-8005:8001-8005"
    volumes:
      # - "./nginx/cert/gamenews.pem:/etc/nginx/cert/gamenews.pem"
      # - "./nginx/cert/gamenews.key:/etc/nginx/cert/gamenews.key"
      - "./nginx/nginx-base.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx-stream-proxy.conf:/etc/nginx/stream.conf.d/nginx-stream-proxy.conf"
      - "./nginx/nginx-http-proxy.conf:/etc/nginx/conf.d/default.conf"
    restart: always  

