version: "2"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8001-8005:8001-8005"
    volumes:
      - "./nginx/cert/music.pem:/etc/nginx/cert/music.pem"
      - "./nginx/cert/music.key:/etc/nginx/cert/music.key"
      - "./nginx/nginx-base.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx-stream-proxy.conf:/etc/nginx/stream.conf.d/nginx-stream-proxy.conf"
      - "./nginx/nginx-http-proxy.conf:/etc/nginx/conf.d/default.conf"
    restart: always  

  frp:
    image: cloverzrg/frps-docker
    container_name: frp
    ports:
      - "7001:7001"
      - "7500:7500"
    volumes:
      - "./frp/frps.ini:/conf/frps.ini"
    restart: always  
